---
- name: Download cloudflared binary arm64
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/download/{{cloudflared_version}}/cloudflared-linux-arm64
    checksum: sha256:{{cloudflared_checksum}}
    dest: /usr/local/bin/cloudflared
    owner: root
    group: root
    mode: 0755
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")